FROM node:25-alpine AS base

WORKDIR /app

COPY package*.json ./
RUN npm install --no-audit --no-fund

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

COPY . .

RUN npm run build

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["npm", "start"]