FROM node:22-alpine

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /workspace

# Copy workspace files
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY shared ./shared
COPY services/chariot/frontend ./services/chariot/frontend

# Install dependencies
RUN pnpm install --frozen-lockfile

WORKDIR /workspace/services/chariot/frontend

EXPOSE ${CHARIOT_FRONT_PORT}

CMD ["pnpm", "run", "dev"]