import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import { KeycloakProvider } from "@/providers/KeycloakProvider";
import ToastContainer from "@/components/ToastContainer";
import LocaleDetector from "@/components/LocaleDetector";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { locales } from "@/i18n/request";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chariot App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${interTight.variable} antialiased bg-[url('/background.svg')] bg-cover font-sans`}>
        <NextIntlClientProvider messages={messages}>
          <KeycloakProvider>
            <LocaleDetector />
            <ToastContainer />
            {children}
          </KeycloakProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
