name: Pull Request
description: Crée une Pull Request standard avec contrôles développeur et reviewer
title: ""
labels: []
body:
  - type: input
    id: ticket
    attributes:
      label: Lien vers le ticket
      description: Lien permettant d'accéder facilement au ticket associé.
      placeholder: "Exemple : https://github.com/ton-org/ton-repo/issues/123"
    validations:
      required: true

  - type: checkboxes
    id: controles_dev
    attributes:
      label: Contrôles pour le développeur
      description: Vérifie que tout est prêt avant la soumission.
      options:
        - label: J'ai testé mes changements localement
        - label: J'ai ajouté/mis à jour la documentation (si nécessaire)
        - label: J'ai ajouté des tests pour couvrir mes changements

  - type: checkboxes
    id: controles_reviewer
    attributes:
      label: Contrôles pour le reviewer
      description: Points à vérifier pendant la revue de code.
      options:
        - label: La branche d’origine et la branche de destination sont correctes
        - label: Les changements ont été résolus et les remarques ajoutées (si nécessaire)
        - label: Les changements ont été testés

  - type: textarea
    id: notes_reviewer
    attributes:
      label: Notes pour le reviewer
      description: Ajoute ici des informations ou remarques utiles pour la relecture.
      placeholder: |
        Exemple :
        - Le test sur le module X est temporaire
        - La dépendance Y devra être revue