FROM node:25-alpine

WORKDIR /app

# Copier uniquement package.json et package-lock.json d'abord
COPY package*.json ./

# Installer les dépendances dans le container (architecture Linux)
RUN npm ci

# Copier le reste des fichiers
COPY . .

EXPOSE ${FRONT_PORT}

CMD ["npm", "run", "dev"]