# Integration overrides
include:
  #- path: ./infrastructure/compose.yml
  #  env_file: .env

  # Chariot microservice (backend + frontend)
  - path: ./services/chariot/compose.integ.yml
    env_file: .env

  # SSO microservice (Keycloak + frontend)
  - path: ./services/sso/compose.integ.yml
    env_file: .env
