# Integration overrides
include:
  - path: ./infrastructure/compose.yml
    env_file: .env

  - path: ./services/chariot/compose.yml
    env_file: .env
  - path: ./services/chariot/compose.integ.yml
    env_file: .env
