# Integration overrides
include:
  - path: ./infrastructure/docker-compose.yml
    env_file: .env

  - path: ./services/chariot/docker-compose.yml
    env_file: .env
  - path: ./services/chariot/docker-compose.integ.yml
    env_file: .env
