
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./backend
    container_name: backend
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules 
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
    command: ["npm", "run", "dev"]


volumes:
  mongodb_data: