FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

COPY . .

# Build the application
RUN npm run build && test -f dist/src/main.js

CMD [ "node", "dist/src/main.js" ]