FROM node:24-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

COPY . .

# Build the application
RUN npm run build  && test -f dist/main.js

CMD [ "node", "dist/main.js" ]