import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import { KeycloakProvider } from "@/providers/KeycloakProvider";
import ToastContainer from "@/components/ToastContainer";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chariot App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <KeycloakProvider>
        <body className={`${interTight.variable} antialiased bg-[url('/background.svg')] bg-cover font-sans`}>
          <ToastContainer />
          {children}
        </body>
      </KeycloakProvider>
    </html>
  );
}
