services:
  chariot-mongo:
    image: mongo:8.0.15
    platform: linux/amd64
    restart: unless-stopped
    command:
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  chariot-backend:
    build:
      context: ../../
      dockerfile: services/chariot/backend/Dockerfile.prod
      args:
        CHARIOT_INTERNAL_API_PORT: ${CHARIOT_INTERNAL_API_PORT:-9000}
    restart: unless-stopped
    volumes:
      - ./backend/logger/logs:/app/logger/logs
    command: ["node", "dist/main.js"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${CHARIOT_INTERNAL_API_PORT}/metrics"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s

  chariot-frontend:
    build:
      context: ../../
      dockerfile: services/chariot/frontend/Dockerfile.prod
      args:
        CHARIOT_FRONT_PORT: ${CHARIOT_FRONT_PORT:-3000}
    restart: unless-stopped
    command: ["node", "server.js"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${CHARIOT_FRONT_PORT:-3000}"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s
