FROM quay.io/keycloak/keycloak:23.0

# Copier le fichier realm dans l'image
COPY keycloak/realm-export.integ.json /opt/keycloak/data/import/realm-export.json

# Copier les thèmes si nécessaire
COPY keycloak/themes /opt/keycloak/themes
