name: ✨ Nouvelle fonctionnalité
description: Proposer une idée ou une amélioration
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Décris la fonctionnalité souhaitée et son utilité
      description: Pourquoi cette amélioration est utile ?
    validations:
      required: true
  - type: textarea
    id: contexte
    attributes:
      label: Contexte
      placeholder: Quel problème cherches-tu à résoudre ?
  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
      placeholder: Comment aimerais-tu que ce soit implémenté ?
