name: Nouveau ticket
description: Template de création d'un ticket pour Chariot
title: "[CHARIOT] "
labels: []
assignees: []
body:

  - type: textarea
    id: contexte
    attributes:
      label: Contexte
      description: Pourquoi cette intégration est-elle nécessaire ?

  - type: textarea
    id: criteres
    attributes:
      label: Critères d’acceptation
      description: Tous les critères qui doivent obligatoirement être faits.
      value: |
        - [ ] 
