FROM node:26-alpine AS builder

WORKDIR /app

RUN apk upgrade --no-cache && apk add --no-cache libc6-compat vips

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:26-alpine AS production

WORKDIR /app

RUN apk upgrade --no-cache && apk add --no-cache libc6-compat vips

COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /app/dist ./dist

CMD ["node", "dist/main"]
