#!/bin/sh
set -e

# Entrypoint script for Prometheus
# Substitutes environment variables into prometheus.yml from template

# Verify template file exists
if [ ! -f "/etc/prometheus/prometheus.yml.template" ]; then
    echo "Error: prometheus.yml.template not found at /etc/prometheus/prometheus.yml.template"
    exit 1
fi

# Set default values for all variables
ENVIRONMENT="${ENVIRONMENT:-development}"
PROMETHEUS_MONITOR_NAME="${PROMETHEUS_MONITOR_NAME:-chariot-monitor}"
PROMETHEUS_SCRAPE_INTERVAL="${PROMETHEUS_SCRAPE_INTERVAL:-15s}"
PROMETHEUS_EVALUATION_INTERVAL="${PROMETHEUS_EVALUATION_INTERVAL:-15s}"
PROMETHEUS_CHARIOT_BACKEND_SCRAPE_INTERVAL="${PROMETHEUS_CHARIOT_BACKEND_SCRAPE_INTERVAL:-10s}"
PROMETHEUS_CADVISOR_SCRAPE_INTERVAL="${PROMETHEUS_CADVISOR_SCRAPE_INTERVAL:-15s}"
PROMETHEUS_NODE_EXPORTER_SCRAPE_INTERVAL="${PROMETHEUS_NODE_EXPORTER_SCRAPE_INTERVAL:-15s}"
PROMETHEUS_MONGODB_SCRAPE_INTERVAL="${PROMETHEUS_MONGODB_SCRAPE_INTERVAL:-15s}"
PROMETHEUS_LOKI_SCRAPE_INTERVAL="${PROMETHEUS_LOKI_SCRAPE_INTERVAL:-15s}"
PROMETHEUS_SELF_TARGET="${PROMETHEUS_SELF_TARGET:-localhost:9090}"
PROMETHEUS_BACKEND_TARGET="${PROMETHEUS_BACKEND_TARGET:-chariot-backend:9000}"
PROMETHEUS_BACKEND_METRICS_PATH="${PROMETHEUS_BACKEND_METRICS_PATH:-/metrics}"
PROMETHEUS_LOKI_METRICS_PATH="${PROMETHEUS_LOKI_METRICS_PATH:-/metrics}"
PROMETHEUS_CADVISOR_TARGET="${PROMETHEUS_CADVISOR_TARGET:-cadvisor:8080}"
PROMETHEUS_NODE_EXPORTER_TARGET="${PROMETHEUS_NODE_EXPORTER_TARGET:-node-exporter:9100}"
PROMETHEUS_MONGODB_EXPORTER_TARGET="${PROMETHEUS_MONGODB_EXPORTER_TARGET:-mongodb-exporter:9216}"
PROMETHEUS_LOKI_EXPORTER_TARGET="${PROMETHEUS_LOKI_EXPORTER_TARGET:-loki:3100}"
PROMETHEUS_ALERTMANAGER_TARGET="${PROMETHEUS_ALERTMANAGER_TARGET:-alertmanager:9093}"
ALERTMANAGER_TIMEOUT="${ALERTMANAGER_TIMEOUT:-10s}"

# Use sed for variable substitution (no dependency on envsubst in Alpine)
sed \
  -e "s|\${ENVIRONMENT}|$ENVIRONMENT|g" \
  -e "s|\${PROMETHEUS_MONITOR_NAME}|$PROMETHEUS_MONITOR_NAME|g" \
  -e "s|\${PROMETHEUS_SCRAPE_INTERVAL}|$PROMETHEUS_SCRAPE_INTERVAL|g" \
  -e "s|\${PROMETHEUS_EVALUATION_INTERVAL}|$PROMETHEUS_EVALUATION_INTERVAL|g" \
  -e "s|\${PROMETHEUS_CHARIOT_BACKEND_SCRAPE_INTERVAL}|$PROMETHEUS_CHARIOT_BACKEND_SCRAPE_INTERVAL|g" \
  -e "s|\${PROMETHEUS_CADVISOR_SCRAPE_INTERVAL}|$PROMETHEUS_CADVISOR_SCRAPE_INTERVAL|g" \
  -e "s|\${PROMETHEUS_NODE_EXPORTER_SCRAPE_INTERVAL}|$PROMETHEUS_NODE_EXPORTER_SCRAPE_INTERVAL|g" \
  -e "s|\${PROMETHEUS_MONGODB_SCRAPE_INTERVAL}|$PROMETHEUS_MONGODB_SCRAPE_INTERVAL|g" \
  -e "s|\${PROMETHEUS_LOKI_SCRAPE_INTERVAL}|$PROMETHEUS_LOKI_SCRAPE_INTERVAL|g" \
  -e "s|\${PROMETHEUS_SELF_TARGET}|$PROMETHEUS_SELF_TARGET|g" \
  -e "s|\${PROMETHEUS_BACKEND_TARGET}|$PROMETHEUS_BACKEND_TARGET|g" \
  -e "s|\${PROMETHEUS_BACKEND_METRICS_PATH}|$PROMETHEUS_BACKEND_METRICS_PATH|g" \
  -e "s|\${PROMETHEUS_LOKI_METRICS_PATH}|$PROMETHEUS_LOKI_METRICS_PATH|g" \
  -e "s|\${PROMETHEUS_CADVISOR_TARGET}|$PROMETHEUS_CADVISOR_TARGET|g" \
  -e "s|\${PROMETHEUS_NODE_EXPORTER_TARGET}|$PROMETHEUS_NODE_EXPORTER_TARGET|g" \
  -e "s|\${PROMETHEUS_MONGODB_EXPORTER_TARGET}|$PROMETHEUS_MONGODB_EXPORTER_TARGET|g" \
  -e "s|\${PROMETHEUS_LOKI_EXPORTER_TARGET}|$PROMETHEUS_LOKI_EXPORTER_TARGET|g" \
  -e "s|\${PROMETHEUS_ALERTMANAGER_TARGET}|$PROMETHEUS_ALERTMANAGER_TARGET|g" \
  -e "s|\${ALERTMANAGER_TIMEOUT}|$ALERTMANAGER_TIMEOUT|g" \
  /etc/prometheus/prometheus.yml.template > /etc/prometheus/prometheus.yml

echo "✓ Prometheus configuration generated from template"

# Change to config directory (relative paths require this)
cd /etc/prometheus

# Execute Prometheus with the provided arguments
exec /bin/prometheus "$@"
