services:
  chariot-mongo:
    image: mongo:latest
    platform: linux/amd64
    container_name: chariot-mongodb-integ
    restart: unless-stopped
    ports:
      - "27017"
    volumes:
      - chariot_mongodb_data:/data/db
      - chariot_mongodb_logs:/var/log/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CHARIOT_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CHARIOT_MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${CHARIOT_MONGO_INITDB_DATABASE}
    command: ["mongod", "--logpath", "/var/log/mongodb/mongod.log", "--logappend"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - chariot-network

  chariot-adventure:
    image: ghcr.io/chariot-group/chariot-adventure-integration:latest
    container_name: chariot-adventure-integ
    restart: unless-stopped
    working_dir: /app
    ports:
      - "9000"
    environment:
      NODE_ENV: integration
      CHARIOT_MONGO_URL: ${CHARIOT_MONGO_URL}
      ADVENTURE_URL: ${ADVENTURE_URL}
      ADVENTURE_VERSION: ${ADVENTURE_VERSION}
      FRONTEND_URL: ${FRONTEND_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      RECEIVER_EMAIL: ${RECEIVER_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      KEYCLOAK_INTERNAL_URL: ${KEYCLOAK_INTERNAL_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      chariot-mongo:
        condition: service_healthy
    networks:
      - chariot-network
      - chariot-group-network-integ
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chariot-adventure-integ.rule=Host(`${ADVENTURE_HOST}`)"
      - "traefik.http.routers.chariot-adventure-integ.entrypoints=websecure"
      - "traefik.http.routers.chariot-adventure-integ.tls.certresolver=letsencrypt"
      - "traefik.http.services.chariot-adventure-integ.loadbalancer.server.port=9000"
      - "traefik.http.routers.chariot-adventure-integ.service=chariot-adventure-integ"
      - "traefik.docker.network=traefik-public"

volumes:
  chariot_mongodb_data:
  chariot_mongodb_logs:
  chariot_adventure_logs:

networks:
  chariot-network:
    driver: bridge
  chariot-group-network-integ:
    external: true
  traefik-public:
    external: true