FROM quay.io/keycloak/keycloak:23.0 as builder

# Configuration pour le build optimisé
ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/server.crt.pem
ENV KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/server.key.pem

# Build optimisé pour la production
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:23.0

COPY --from=builder /opt/keycloak/ /opt/keycloak/

# Répertoire pour les certificats SSL
RUN mkdir -p /opt/keycloak/conf

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
