name: CI - Frontend & Backend

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" || "$GITHUB_REF_NAME" == "integ" ]]; then
            npm ci
          else
            npm install
          fi

      - name: Format frontend
        working-directory: ./frontend
        run: npm run format

      # Décommenter lorsque les tests unitaires sont prêts
      # - name: Run unit tests
      #   working-directory: ./frontend
      #   run: npm test

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" || "$GITHUB_REF_NAME" == "integ" ]]; then
            npm ci
          else
            npm install
          fi

      - name: Format backend
        working-directory: ./backend
        run: npm run format

      # Décommenter lorsque les tests unitaires sont prêts
      # - name: Run unit tests
      #   working-directory: ./backend
      #   run: npm test

      - name: Build backend
        working-directory: ./backend
        run: npm run build